### ISSUE TITLE
Error while save image

### ISSUE THREAD

**Issue by nizhegorodets** [aswinnnn/weheartpy#5]
Hi! i'm trying run this code:

```
from weheartpy import WeHeartIt

whi = WeHeartIt()

cocs = whi.search_collections("anime pfp")
for c in cocs:
    print(c.title, c.link)
    collection = c.get_full_collection()
    print(collection.images, collection.description)

    collection.save("\\collection\\")
```

And catch error:

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/weheart/venv/lib/python3.10/site-packages/weheartpy/models.py", line 134, in save
    f.write(img.content)
TypeError: write() argument must be str, not bytes

What could be the problem?

**Comment by aswinnnn** [comment]
Context: The images weren't being opened to be written with bytes while the image content, infact, were bytes. This would have been a major issue in the upcoming releases so thanks for opening the issue and pointing it out! 

The fix is not on pypi yet, but will be later this day. If you want to use this fix immediately I recommend uninstalling the package with pip `pip uninstall weheartpy` and installing it through the github repo.
```
pip install git+https://github.com/aswinnnn/weheartpy
```

**Comment by aswinnnn** [comment]
I recommend checking out the [package version](https://pypi/projects/weheartpy) on pypi to see if i have released the fix on pypi if you're viewing this later.

**Comment by aswinnnn** [comment]
The fix has been released on PyPi and is recommended to update using 
```
pip install --upgrade weheartpy
```
Thanks for opening the issue and contributing to the module!
